config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  post "/home/user_guest_sign_in", :to => "home#new_user_guest"
  post "/home/hospital_guest_sign_in", :to => "home#new_hospital_guest"
  get "about_user", :to => "home#about_user"
  get "about_hospital", :to => "home#about_hospital"
  resources :chats, only: [:create, :show], param: :room_id
  resources :rooms, only: [:create]

  scope module: :users do
    devise_for :users, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
    }
    get "daily_records/search", :to => "daily_records#search"
    resources :users, only: [:show, :edit, :update, :destroy] do
      get "delete_confirm", :to => "users#delete_confirm"
      resources :medical_histories, except: [:show]
      resources :health_cares, except: [:show]
      get :families, on: :member
      resources :medical_records
    end
    resources :daily_records do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  scope module: :hospitals do
    devise_for :hospitals, controllers: {
      registrations: "hospitals/registrations",
      sessions: "hospitals/sessions",
    }
    get "hospitals/search", :to => "search#search"
    resources :hospitals, only: [:index, :show, :edit, :update]
    resources :medical_relationships, only: [:create, :destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :medical_relationships
  has_many :patients, through: :medical_relationships, source: :user
  has_many :medical_records, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, :address, :email, presence: true
  validates :telphone_number, :postal_code, numericality: { only_integer: true }

  # かかりつけ医の登録をしている患者かどうか
  def patients?(user)
    medical_relationships.find_by(user_id: user.id).present?
  end

  def self.search(content)
    Hospital.where("name LIKE? OR telphone_number LIKE? OR postal_code LIKE? OR address LIKE?",
    "%#{content}%", "#{content}", "#{content}", "%#{content}%")
  end
end

app/controllers/hospitals/confirmations_controller.rb
# frozen_string_literal: true

class Hospitals::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/hospitals/hospitals_controller.rb
class Hospitals::HospitalsController < ApplicationController
  before_action :authenticate_hospital!, except: [:show, :index]
  before_action :all_signed_in, only: [:show, :index]
  before_action :correct_hospital, only: [:edit]
  before_action :set_hospital, only: [:show, :edit, :update]
  before_action :check_guest_hospital, only: [:update]

  def show
    # 個人利用者がアクセスしている場合
    if current_user.present?
      @room1 = Room.where(user_id: current_user.id)
      @room1.each do |r|
        @hospital.rooms.each do |hr|
          if r.id == hr.id
            @isRoom = true
            @roomId = r.id
          end
        end
      end
      unless @isRoom
        @room = Room.new
      end
    end
  end

  def edit
  end

  def update
    if @hospital.update(hospital_params)
      redirect_to hospital_path(@hospital)
      flash[:notice] = '更新しました'
    else
      render "edit"
    end
  end

  def index
    @hospitals = Hospital.all
  end

  private

  def set_hospital
    @hospital = Hospital.find(params[:id])
  end

  def hospital_params
    params.require(:hospital).permit(:name, :email, :postal_code, :address, :telphone_number)
  end

  def check_guest_hospital
    if current_hospital.email == 'guest_hospital@example.com'
      redirect_to hospital_path(current_hospital), alert: 'ゲストユーザーの情報は変更できません。'
    end
  end
end

app/controllers/hospitals/medical_relationships_controller.rb
class Hospitals::MedicalRelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    family = current_user.medical_relationships.build(
      hospital_id: params[:hospital][:hospital_id])
    family.save
    redirect_to hospital_path(params[:hospital][:hospital_id])
    flash[:notice] = 'かかりつけ医登録しました'
  end

  def destroy
    family = current_user.medical_relationships.find_by(
      hospital_id: params[:hospital][:hospital_id])
    family.destroy
    redirect_to hospital_path(params[:hospital][:hospital_id])
    flash[:alert] = 'かかりつけ医登録を解除しました'
  end
end

app/controllers/hospitals/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Hospitals::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/hospitals/passwords_controller.rb
# frozen_string_literal: true

class Hospitals::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/hospitals/registrations_controller.rb
# frozen_string_literal: true

class Hospitals::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  before_action :configure_sign_up_params, only: [:create]

  def after_sign_up_path_for(resource)
    hospital_path(current_hospital)
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :name, :postal_code, :address, :telphone_number,
    ])
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/hospitals/search_controller.rb
class Hospitals::SearchController < ApplicationController
  def search
    @content = params[:search][:content]
    @hospitals = Hospital.search(@content)
  end
end

app/controllers/hospitals/sessions_controller.rb
# frozen_string_literal: true

class Hospitals::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    hospital_path(current_hospital)
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/hospitals/unlocks_controller.rb
# frozen_string_literal: true

class Hospitals::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/hospitals/_hospital.html.erb
<div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <% if current_hospital.id == hospital.id %>
    <h2>マイページ</h2>
  <% else %>
    <h2>医療機関詳細</h2>
  <% end %>
</div>

<div class="row"></div>
  <div class="col-md-6 col-md-offset-3 col-xs-12">
    <table class="table col text-center">
      <thead>
        <tr>
          <th colspan="2" class="col text-center"><h3><b><%= hospital.name %></b></h3></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th class="col text-center">電話番号</th>
          <td class="col text-center"><%= hospital.telphone_number %></td>
        </tr>
        <tr>
          <th class="col text-center">郵便番号</th>
          <td class="col text-center"><%= hospital.postal_code %></td>
        </tr>
        <tr>
          <th class="col text-center">住所</th>
          <td class="col text-center"><%= hospital.address %></td>
        </tr>
        <% if current_hospital.id == hospital.id %>
          <tr>
            <th class="col text-center">登録情報</th>
            <td class="col text-center"><%= link_to "編集する", edit_hospital_path(hospital), class: "btn btn-primary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% if current_hospital.id == hospital.id %>
  <div class="col-sm-12 col-md-6">
    <div class="hospital-select">
      <i class="fas fa-user-check"></i>
      <h3><b class="patient-page">患者ページ</b></h3>
      <h4>患者さまによる「病歴」「健康管理」<br>「日常記録」の投稿を確認できます！<br>
      その他、チャットでの簡易連絡も！<br>
      </h4>
    </div>
  </div>
  <div class="col-sm-12 col-md-6">
    <div class="hospital-select">
      <i class="fas fa-file-medical"></i>
      <h3><b class="medical-page">診療記録</b></h3>
      <h4>診療記録が作成でき、<br>患者にはメールで通知が届きます！<br>
      他医療機関での診察内容の確認も！<br>
      </h4>
    </div>
  </div>

  <div class="col-xs-12">
    <div class="hospital-show-patient">
      <div class="hospital-show-patient-head">
        <h3>患者一覧</h3>
        <h4>患者さまがかかりつけ医の登録をすると<br>
        一覧に表示されます！</h4>
      </div>

      <% if hospital.patients.present? %>
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th class="col text-center">患者名</th>
                <th class="col text-center">電話番号</th>
                <th class="col text-center">郵便番号</th>
                <th class="col text-center">住所</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% hospital.patients.each do |patient| %>
                <tr>
                  <td class="col text-center"><%= patient.last_name %></td>
                  <td class="col text-center"><%= patient.telphone_number %></td>
                  <td class="col text-center"><%= patient.postal_code %></td>
                  <td class="col text-center"><%= patient.address %></td>
                  <th class="col text-center">
                    <%= link_to "患者ページ", user_path(patient), class: "btn btn-warning btn-sm" %>
                    <%= link_to "診療記録", user_medical_records_path(patient), class: "btn btn-success btn-sm" %>
                  </th>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        <h4 class="col text-center">患者はいません</h4>
      <% end %>
    </div>
  </div>
<% end %>

app/views/hospitals/hospitals/_index.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th class="col text-center col-xs-3">医療機関名</th>
        <th class="col text-center col-xs-2">電話番号</th>
        <th class="col text-center col-xs-2">郵便番号</th>
        <th class="col text-center col-xs-5">住所</th>
      </tr>
    </thead>
    <tbody>
      <% hospitals.each do |hospital| %>
        <tr class="col text-center">
          <td>
            <%= link_to hospital_path(hospital) do %>
              <%= hospital.name %>
            <% end %>
          </td>
          <td class="col text-center"><%= hospital.telphone_number %></td>
          <td class="col text-center"><%= hospital.postal_code %></td>
          <td class="col text-center"><%= hospital.address %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/hospitals/hospitals/_user.html.erb
<div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <h2>医療機関詳細</h2>
</div>

<div class="col-md-6 col-md-offset-3 col-xs-12">
  <table class="table col text-center">
    <thead>
      <tr>
        <th colspan="2" class="col text-center"><h3><b><%= hospital.name %></b></h3></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th class="col text-center">電話番号</th>
        <td class="col text-center"><%= hospital.telphone_number %></td>
      </tr>
      <tr>
        <th class="col text-center">郵便番号</th>
        <td class="col text-center"><%= hospital.postal_code %></td>
      </tr>
      <tr>
        <th class="col text-center">住所</th>
        <td class="col text-center"><%= hospital.address %></td>
      </tr>
    </tbody>
  </table>

  <div class="col-xs-12">
    <div class="hospital-select">
      <i class="fas fa-user-md"></i>
      <h3><b>かかりつけ医登録</b></h3>
      <h4>健康管理や日常記録など、幅広く共有できます！<br>
      診療記録の作成や、チャットでの簡易連絡も！<br>
      <span class="attention">※かかりつけ医登録の医療機関同士では、<br>
      それぞれの診療記録が共有されることとなります。</span></h4>

      <% if current_user.families?(hospital) %>
        <div>
          <%= form_with model: hospital, url: medical_relationship_path(user_id: current_user.id, hospital_id: hospital.id), method: :delete, local: true do |f| %>
            <%= f.hidden_field :hospital_id, :value => hospital.id %>
            <%= f.submit "登録を外す", class: "btn btn-danger" %>
          <% end %>

          <h4>チャットはこちらから！</h4>
          <% if isRoom == true %>
      			<%= link_to "チャットのつづきへ", chat_path(roomId, hospital_id: hospital.id, user_id: current_user.id), class: "btn btn-warning" %>
      		<% else %>
      			<%= form_with(model:room, url: rooms_path, local: true) do |f| %>
    					<%= f.hidden_field :hospital_id, value: hospital.id %>
    					<%= f.hidden_field :user_id, value: current_user.id %>
      				<%= f.submit "チャットをはじめる", class: "btn btn-primary" %>
      			<% end %>
      		<% end %>
    		</div>

      <% else %>
        <%= form_with model: hospital, url: medical_relationships_path, method: :post, local: true do |f| %>
          <%= f.hidden_field :hospital_id, :value => hospital.id %>
          <%= f.submit "登録する", class: "btn btn-primary" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="col text-center">
    <%= link_to "かかりつけ医一覧に戻る", families_user_path(current_user.id), class: "btn btn-success" %>
  </div>
</div>

app/views/hospitals/hospitals/edit.html.erb
<div class="hospital-edit-container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
      <h2 class="col text-center">登録情報編集</h2>

      <%= form_with model: @hospital, url: hospital_path(@hospital), local: true do |f| %>
        <%= render "hospitals/shared/error_messages", resource: @hospital %>

    　　<div class="hospital-input">
          <div class="hospital-input-form">
            <%= f.label :name, "医療機関名" %><br>
            <%= f.text_field :name, autofocus: true, class: "form-control" %><br>
          </div>

          <div class="hospital-input-form">
            <%= f.label :email, "メールアドレス" %><br>
            <%= f.email_field :email, type: "email", autocomplete: "email", class: "form-control" %><br>
          </div>

          <div class="hospital-input-form">
            <%= f.label :postal_code, "郵便番号（ハイフンなし）" %><br>
            <%= f.text_field :postal_code, class: "form-control" %><br>
          </div>

          <div class="hospital-input-form">
            <%= f.label :address, "住所" %><br>
            <%= f.text_field :address, class: "form-control" %><br>
          </div>

          <div class="hospital-input-form">
            <%= f.label :telphone_number, "電話番号（ハイフンなし）" %><br>
            <%= f.text_field :telphone_number, type: "tel", class: "form-control" %><br>
          </div>
        </div>

        <div class="hospital-input-button col text-center">
          <p><%= f.submit "編集する", class: "btn btn-warning" %></p>
        </div>
      <% end %>
     </div>
  </div>
</div>

app/views/hospitals/hospitals/index.html.erb
<div class="hospital-index-container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
      <h2>医療機関一覧</h2>
    </div>

    <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
      <div class="row">
        <div class="hospital-search">
          <%= form_with(scope: :search, url: hospitals_search_path, method: :get, local: true) do |f| %>
            <%= f.text_field :content %>
            <%= f.submit "検索" %>
          <% end %>
        </div>
      </div>

      <div class="hospital-index">
        <%= render "index", hospitals: @hospitals %>
      </div>
      <div class="col text-right">
        <%= link_to "戻る", :back, class: "btn btn-success btn-lg" %>
      </div>
    </div>
  </div>
</div>

app/views/hospitals/hospitals/show.html.erb
<div class="hospital-show-container">
  <div class="row">
    <% if current_user.present? %>　<!--個人利用者の場合-->
      <%= render "user", hospital: @hospital, isRoom: @isRoom, roomId: @roomId, room: @room %>
    <% else %> <!--医療関係者の場合-->
      <%= render "hospital", hospital: @hospital %>
    <% end %>
  </div>
</div>