config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  post "/home/user_guest_sign_in", :to => "home#new_user_guest"
  post "/home/hospital_guest_sign_in", :to => "home#new_hospital_guest"
  get "about_user", :to => "home#about_user"
  get "about_hospital", :to => "home#about_hospital"
  resources :chats, only: [:create, :show], param: :room_id
  resources :rooms, only: [:create]

  scope module: :users do
    devise_for :users, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
    }
    get "daily_records/search", :to => "daily_records#search"
    resources :users, only: [:show, :edit, :update, :destroy] do
      get "delete_confirm", :to => "users#delete_confirm"
      resources :medical_histories, except: [:show]
      resources :health_cares, except: [:show]
      get :families, on: :member
      resources :medical_records
    end
    resources :daily_records do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  scope module: :hospitals do
    devise_for :hospitals, controllers: {
      registrations: "hospitals/registrations",
      sessions: "hospitals/sessions",
    }
    get "hospitals/search", :to => "search#search"
    resources :hospitals, only: [:index, :show, :edit, :update]
    resources :medical_relationships, only: [:create, :destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :hospital, optional: true
  belongs_to :room

  validates :message, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :daily_record

  validates :comment, presence: true
end

app/models/daily_record.rb
class DailyRecord < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :theme, :introduction, :genre, presence: true
  attachment :daily_image

  enum genre: {
    食事: 0,
    運動: 1,
    その他: 2,
  }

  def favorited_by?(user)
    favorites.where(user_id: user.id).present?
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :daily_record
end

app/models/health_care.rb
class HealthCare < ApplicationRecord
  belongs_to :user

  validates :body_weight_or_max_blood_pressure_or_min_blood_pressure_or_blood_sugar, :date, presence: true
  validates :body_weight, :max_blood_pressure, :min_blood_pressure, :blood_sugar,numericality: { only_integer: true }, allow_blank: true

  # 体重・最高血圧・最低血圧・血糖値のいずれかが入力されているか
  def body_weight_or_max_blood_pressure_or_min_blood_pressure_or_blood_sugar
    body_weight.presence || max_blood_pressure.presence || min_blood_pressure.presence || blood_sugar.presence
  end
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :medical_relationships
  has_many :patients, through: :medical_relationships, source: :user
  has_many :medical_records, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, :address, :email, presence: true
  validates :telphone_number, :postal_code, numericality: { only_integer: true }

  # かかりつけ医の登録をしている患者かどうか
  def patients?(user)
    medical_relationships.find_by(user_id: user.id).present?
  end

  def self.search(content)
    Hospital.where("name LIKE? OR telphone_number LIKE? OR postal_code LIKE? OR address LIKE?",
    "%#{content}%", "#{content}", "#{content}", "%#{content}%")
  end
end

app/models/medical_history.rb
class MedicalHistory < ApplicationRecord
  belongs_to :user

  validates :disease, :started_on, :treatment, :hospital, presence: true
end

app/models/medical_record.rb
class MedicalRecord < ApplicationRecord
  validates :user_id, :hospital_id, :start_time, :doctor, :disease, :treatment, presence: true
  belongs_to :user
  belongs_to :hospital
end

app/models/medical_relationship.rb
class MedicalRelationship < ApplicationRecord
  belongs_to :user
  belongs_to :hospital
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  belongs_to :hospital
  has_many :chats, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :daily_records, dependent: :destroy
  has_many :medical_histories, dependent: :destroy
  has_many :health_cares, dependent: :destroy
  has_many :medical_records, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  has_many :medical_relationships
  has_many :families, through: :medical_relationships, source: :hospital

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :address, :email,
            presence: true
  validates :telphone_number, :postal_code, numericality: { only_integer: true }
  attachment :profile_image

  # かかりつけ医の登録がされているかどうか
  def families?(hospital)
    medical_relationships.find_by(hospital_id: hospital.id).present?
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def create
    @chat = Chat.new(chat_params)
    @chat.save!
    @room = Room.find(params[:chat][:room_id])
    @chats = @room.chats
  end

  def show
    @room = Room.find(params[:room_id])
    @user = User.find(params[:user_id])
    @hospital = Hospital.find(params[:hospital_id])
    @chats = @room.chats
    @chat = Chat.new
  end

  def chat_params
    params.require(:chat).permit(:message, :room_id, :user_id, :hospital_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def new_user_guest
    user = User.find_or_create_by!(
      last_name: "カープ",
      first_name: "坊や",
      last_name_kana: "カープ",
      first_name_kana: "ボウヤ",
      email: "guest_user_@example.com",
      postal_code: "0000000",
      address: "広島県",
      telphone_number: "00000000000"
    ) do |user|
      user.password = SecureRandom.urlsafe_base64
    end
    sign_in user
    redirect_to user_path(current_user), notice: "ゲストユーザー（個人利用者用）としてログインしました！"
  end

  def new_hospital_guest
    hospital = Hospital.find_or_create_by!(
      name: "広島病院",
      email: "guest_hospital@example.com",
      postal_code: "0000000",
      address: "広島県",
      telphone_number: "00000000000"
    ) do |hospital|
      hospital.password = SecureRandom.urlsafe_base64
    end
    sign_in hospital
    redirect_to hospital_path(current_hospital), notice: "ゲストユーザー（医療関係者用）としてログインしました！"
  end

  def about_user
  end

  def about_hospital
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/health_cares_helper.rb
module HealthCaresHelper
  def health_care(value)
    value ||= '-'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about_hospital.erb
<div class="about-container">
  <div class="row">
    <h1><span>医療関係者さま</span></h1>
    <h2><b>患者さまの健康状態を<br><span>正しく管理してみませんか？</span></b></h2>

    <div class="col-sm-12 col-md-4">
      <div class="about-icon">
        <i class="far fa-calendar-check"></i>
        <h3><b>毎日の体調確認に！</b></h3>
        <h4>患者さまの食事・運動から、<br>血圧などの数値まで、<br>
        幅広く管理することができます！<br>
        診察時にまとめて話を聞く必要がなく、<br>かつ内容も漏れがありません！</h4>
      </div>
    </div>

    <div class="col-sm-12 col-md-4">
      <div class="about-icon">
        <i class="fas fa-share-square"></i>
        <h3><b>診療内容の共有に！</b></h3>
        <h4>診療内容を作成して、<br>患者さまと共有できるので、<br>
        治療方針の意識統一ができます！<br>
        データとして残るため、<br>伝え忘れもありません！</h4>
      </div>
    </div>

    <div class="col-sm-12 col-md-4">
      <div class="about-icon">
        <i class="fas fa-hospital-alt"></i>
        <h3><b>他医療機関での<br>治療内容の把握に！</b></h3>
        <h4>患者さまが他の医療機関で治療した内容を<br>
        確認することができます！</h4>
      </div>
    </div>
  </div>
  <div class="attention">※患者さまにより、「かかりつけ医の登録」をしてもらうことで、上記内容が可能となります。</div>
  <% unless current_hospital.present? %>
    <div class="about-new-btn col text-center">
      <%= link_to "さっそく新規登録！", new_hospital_registration_path, class: "btn btn-new", data: {"turbolinks" => false} %>
    </div>
  <% end %>
</div>

app/views/home/about_user.erb
<div class="about-container">
  <div class="row">
    <h1><span>個人利用者さま</span></h1>
    <h2><b><span>手軽に健康管理してみませんか？</span></b></h2>

    <div class="col-sm-12 col-md-4">
      <div class="about-icon">
        <i class="fas fa-pencil-alt"></i>
        <h3><b>日々の記録をお手軽に！</b></h3>
        <h4>食事などの日常記録から、血圧・血糖値まで、<br>幅広く記録できます！<br>
        今までの病歴もまとめておくと、<br>いざという時に便利！<br>
        記録忘れがないよう、<br>毎朝のメール機能まで！</h4>
      </div>
    </div>

    <div class="col-sm-12 col-md-4">
      <div class="about-icon">
        <i class="fas fa-hospital-alt"></i>
        <h3><b>かかりつけの医療機関との<br>情報共有が密に！</b></h3>
        <h4>かかりつけ医の登録をすると、<br>
        日常記録だけでなく、<br>診察内容の共有も確認できます！<br>
        かかりつけの医療機関同士で、<br>治療内容を共有してもらうことも！</h4>
      </div>
    </div>

    <div class="col-sm-12 col-md-4">
      <div class="about-icon">
        <i class="fas fa-users"></i>
        <h3><b>健康意識を持った仲間と共に！</b></h3>
        <h4>食事や運動といった<br>日々の取り組みについて、<br>
        コメントやいいねでお互い応援しましょう！<br>
        参考になる取り組みを発見できるかも！</h4>
      </div>
    </div>
  </div>
  <div class="attention">※かかりつけ医登録をしている医療機関同士では、診療記録が共有されることとなるので、ご注意ください。</div>
  <% unless current_user.present? %>
    <div class="about-new-btn col text-center">
      <%= link_to "さっそく新規登録！", new_user_registration_path, class: "btn btn-new", data: {"turbolinks" => false} %>
    </div>
  <% end %>
</div>

app/views/home/top.html.erb
<div class="top-container">
  <% if current_user.present? || current_hospital.present? %>
    <h4 class="top-login-message">すでにログインしています</h4>
  <% else %>
    <div class="top-image">
      <div class="background-black">
        <div class="top-content">
          <h3 class="top-text"><b>健康と医療を管理して、<br>毎日をもっと楽しく！</b></h3>
        </div>

        <div class="row">
          <div class="col-sm-12 col-md-6">
            <div class="user-top">
              <i class="fas fa-user"></i>
              <h4><b>個人利用者さま</b></h4>
              <div class="col text-center">
                <%= link_to "はじめまして", about_user_path, class: "btn btn-primary" %>
                <%= link_to "ログイン", new_user_session_path, class: "btn btn-success" %>
                <%= link_to 'ゲストログイン（閲覧用）', home_user_guest_sign_in_path, method: :post, class: "btn btn-warning" %>
              </div>
            </div>
          </div>

          <div class="col-sm-12 col-md-6">
            <div class="hospital-top">
              <i class="fas fa-user-md"></i>
              <h4><b>医療関係者さま</b></h4>
              <div class="col text-center">
                <%= link_to "はじめまして", about_hospital_path, class: "btn btn-primary" %>
                <%= link_to "ログイン", new_hospital_session_path, class: "btn btn-success" %>
                <%= link_to 'ゲストログイン（閲覧用）', home_hospital_guest_sign_in_path, method: :post, class: "btn btn-warning" %>
              </div>
            </div>
          </div>
        </div>

        <div class="mouse">
          <h4><b>What's "Joy Health!"?</b></h4>
          <i class="fas fa-caret-square-down" id="can-button"></i>
          <div class="row" id="slide">
            <div class="what col-xs-8 col-xs-offset-2">
              <h3><b>できること基本２ヶ条</b></h3>
              <i class="fas fa-scroll"></i>
              <div class="row">
                <div class="col-sm-12 col-md-6">
                  <div class="can">
                    <h3>その１　投稿</h3>
                    <div class="can-content">
                      <i class="fas fa-user"></i>
                      <h5><b>＜個人利用者＞</b></h5>
                      <p>①日常記録 （食事、運動、その他）</p>
                      <p>②健康管理（体重、血圧、血糖値）</p>
                      <p>③病歴（現在治療中も含む）</p>
                    </div>
                    <div class="can-content">
                      <i class="fas fa-user-md"></i>
                      <h5><b>＜医療関係者＞</b></h5>
                      <p>診療記録</p>
                    </div>
                  </div>
                </div>
                <div class="col-sm-12 col-md-6">
                  <div class="can">
                    <h3>その２　情報共有</h3>
                    <div class="can-content">
                      <i class="fas fa-user-friends"></i>
                      <h5><b>＜個人利用者同士＞</b></h5>
                      <p>日常記録のみ</p>
                    </div>
                    <div class="can-content">
                      <i class="fas fa-hospital-user"></i>
                      <h5><b>＜個人利用者と医療機関＞</b></h5>
                      <p>お互いの全ての投稿</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="can-finish">
                <span>個人は日々の健康状態をより手軽かつ正確に管理でき、<br>
                医療機関は正しく患者の状態を把握することで、より適切な医療が可能になります！</span>
                <h5>その他にも、できることが盛りだくさん！<br>
                さあ、あなたも「Joy Health!」で楽しい毎日をはじめてみよう！！</h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>