config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  post "/home/user_guest_sign_in", :to => "home#new_user_guest"
  post "/home/hospital_guest_sign_in", :to => "home#new_hospital_guest"
  get "about_user", :to => "home#about_user"
  get "about_hospital", :to => "home#about_hospital"
  resources :chats, only: [:create, :show], param: :room_id
  resources :rooms, only: [:create]

  scope module: :users do
    devise_for :users, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
    }
    get "daily_records/search", :to => "daily_records#search"
    resources :users, only: [:show, :edit, :update, :destroy] do
      get "delete_confirm", :to => "users#delete_confirm"
      resources :medical_histories, except: [:show]
      resources :health_cares, except: [:show]
      get :families, on: :member
      resources :medical_records
    end
    resources :daily_records do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  scope module: :hospitals do
    devise_for :hospitals, controllers: {
      registrations: "hospitals/registrations",
      sessions: "hospitals/sessions",
    }
    get "hospitals/search", :to => "search#search"
    resources :hospitals, only: [:index, :show, :edit, :update]
    resources :medical_relationships, only: [:create, :destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/health_care.rb
class HealthCare < ApplicationRecord
  belongs_to :user

  validates :body_weight_or_max_blood_pressure_or_min_blood_pressure_or_blood_sugar, :date, presence: true
  validates :body_weight, :max_blood_pressure, :min_blood_pressure, :blood_sugar,numericality: { only_integer: true }, allow_blank: true

  # 体重・最高血圧・最低血圧・血糖値のいずれかが入力されているか
  def body_weight_or_max_blood_pressure_or_min_blood_pressure_or_blood_sugar
    body_weight.presence || max_blood_pressure.presence || min_blood_pressure.presence || blood_sugar.presence
  end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @daily_record = DailyRecord.find(params[:daily_record_id])
    comment = current_user.comments.new(comment_params)
    comment.daily_record_id = @daily_record.id
    comment.save
  end

  def destroy
    @daily_record = DailyRecord.find(params[:daily_record_id])
    Comment.find_by(id: params[:id], daily_record_id: params[:daily_record_id]).destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/daily_records_controller.rb
class Users::DailyRecordsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :all_signed_in, only: [:show]
  before_action :correct_daily_record_user, only: [:edit]
  before_action :set_daily_record, only: [:show, :edit, :update, :destroy]

  def new
    @daily_record = DailyRecord.new
  end

  def create
    @daily_record = DailyRecord.new(daily_record_params)
    @daily_record.user_id = current_user.id
    if @daily_record.save
      redirect_to user_path(current_user)
      flash[:notice] = '投稿しました'
    else
      render "new"
    end
  end

  def index
    @daily_records = DailyRecord.includes(:user, :comments, :favorites).all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @daily_record.update(daily_record_params)
      redirect_to daily_record_path(@daily_record)
      flash[:notice] = '更新しました'
    else
      render "edit"
    end
  end

  def destroy
    @daily_record.destroy
    redirect_to user_path(current_user)
    flash[:alert] = '削除しました'
  end

  def search
    @daily_records = DailyRecord.includes(:user, :comments, :favorites).where(genre: params[:genre]).order(created_at: :desc)
  end

  private

  def set_daily_record
    @daily_record = DailyRecord.find(params[:id])
  end

  def daily_record_params
    params.require(:daily_record).permit(:theme, :introduction, :daily_image, :genre)
  end
end

app/controllers/users/favorites_controller.rb
class Users::FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @daily_record = DailyRecord.find(params[:daily_record_id])
    @favorite = current_user.favorites.new(daily_record_id: @daily_record.id)
    @favorite.save
  end

  def destroy
    @daily_record = DailyRecord.find(params[:daily_record_id])
    favorite = current_user.favorites.find_by(daily_record_id: @daily_record.id)
    favorite.destroy
  end
end

app/controllers/users/health_cares_controller.rb
class Users::HealthCaresController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :correct_relationship_id, only: [:index]
  before_action :correct_user_id, only: [:new, :edit]
  before_action :set_health_care, only: [:edit, :update, :destroy]

  def new
    @health_care = HealthCare.new
  end

  def create
    @health_care = HealthCare.new(health_care_params)
    @health_care.user_id = current_user.id
    if @health_care.save
      redirect_to user_health_cares_path(current_user)
      flash[:notice] = '投稿しました'
    else
      render "new"
    end
  end

  def index
    @user = User.find(params[:user_id])
    @health_cares = @user.health_cares.order(date: :desc).page(params[:page]).per(10)
    respond_to do |format|
      format.html do
      end
      format.csv do
        send_data render_to_string, filename: "数値記録.csv", type: :csv
      end
    end
  end

  def edit
  end

  def update
    if @health_care.update(health_care_params)
      redirect_to user_health_cares_path(current_user)
      flash[:notice] = '更新しました'
    else
      render "edit"
    end
  end

  def destroy
    @health_care.destroy
    redirect_to user_health_cares_path(current_user)
    flash[:alert] = '削除しました'
  end

  private

  def set_health_care
    @health_care = HealthCare.find(params[:id])
  end

  def health_care_params
    params.require(:health_care).permit(
      :body_weight, :max_blood_pressure, :min_blood_pressure, :blood_sugar, :date)
  end
end

app/controllers/users/medical_histories_controller.rb
class Users::MedicalHistoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :correct_relationship_id, only: [:index]
  before_action :correct_user_id, only: [:new, :edit]
  before_action :set_medical_history, only: [:edit, :update, :destroy]

  def new
    @medical_history = MedicalHistory.new
  end

  def create
    @medical_history = MedicalHistory.new(medical_history_params)
    @medical_history.user_id = current_user.id
    if @medical_history.save
      redirect_to user_medical_histories_path(current_user)
      flash[:notice] = '投稿しました'
    else
      render "new"
    end
  end

  def index
    @user = User.find(params[:user_id])
    @medical_histories = @user.medical_histories.order(started_on: :desc).page(params[:page]).per(5)
    respond_to do |format|
      format.html do
      end
      format.csv do
        send_data render_to_string, filename: "病歴.csv", type: :csv
      end
    end
  end

  def edit
  end

  def update
    if @medical_history.update(medical_history_params)
      redirect_to user_medical_histories_path(current_user)
      flash[:notice] = '更新しました'
    else
      render "edit"
    end
  end

  def destroy
    @medical_history.destroy
    redirect_to user_medical_histories_path(current_user)
    flash[:alert] = '削除しました'
  end

  private

  def set_medical_history
    @medical_history = MedicalHistory.find(params[:id])
  end

  def medical_history_params
    params.require(:medical_history).permit(
      :disease, :started_on, :finished_on, :treatment, :hospital)
  end
end

app/controllers/users/medical_records_controller.rb
class Users::MedicalRecordsController < ApplicationController
  before_action :authenticate_hospital!, except: [:index, :show]
  before_action :correct_relationship_id, only: [:index, :show]
  before_action :family_hospital_id, only: [:new, :edit]
  before_action :set_medical_record, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  def new
    @medical_record = MedicalRecord.new
  end

  def create
    @medical_record = MedicalRecord.new(medical_record_params)
    @medical_record.hospital_id = current_hospital.id
    @medical_record.user_id = params[:user_id]
    if @medical_record.save
      NotificationMailer.medical_record_to_user(@user, @medical_record).deliver
      redirect_to user_medical_records_path(@user)
      flash[:notice] = '投稿しました'
    else
      render "new"
    end
  end

  def index
    @medical_records = MedicalRecord.where(user_id: params[:user_id]).order(
      start_time: :desc).page(params[:page]).per(5)
  end

  def show
  end

  def edit
  end

  def update
    if @medical_record.update(medical_record_params)
      redirect_to user_medical_record_path(@user)
      flash[:notice] = '更新しました'
    else
      render "edit"
    end
  end

  def destroy
    @medical_record.destroy
    redirect_to user_medical_records_path(@user)
    flash[:alert] = '削除しました'
  end

  private

  def set_medical_record
    @medical_record = MedicalRecord.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def medical_record_params
    params.require(:medical_record).permit(:start_time, :doctor, :disease, :treatment)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  before_action :configure_sign_up_params, only: [:create]

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :last_name, :first_name, :last_name_kana, :first_name_kana,
      :postal_code, :address, :telphone_number,
    ])
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show, :families]
  before_action :correct_relationship, only: [:families]
  before_action :correct_user, only: [:edit]
  before_action :correct_user_id, only: [:delete_confirm]
  before_action :set_user, except: [:delete_confirm, :destroy]
  before_action :check_guest_user, only: [:update, :destroy]

  def show
    @daily_records = @user.daily_records.includes(:favorites, :comments).order(created_at: :desc).page(params[:page]).per(5)
    @guest_user = User.find_by(email: "guest_user_@example.com")
    # 医療機関関係者がアクセスしている場合
    if current_hospital.present?
      @room1 = Room.where(hospital_id: current_hospital.id)
      @room1.each do |r|
        @user.rooms.each do |ur|
          if r.id == ur.id
            @isRoom = true
            @roomId = r.id
          end
        end
      end
      unless @isRoom
        @room = Room.new
      end
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:notice] = '更新しました'
    else
      render "edit"
    end
  end

  def delete_confirm
    @user = User.find(params[:user_id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
    flash[:notice] = '退会しました'
  end

  def families
    @hospitals = @user.families
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email,
    :postal_code, :address, :telphone_number, :profile_image)
  end

  def check_guest_user
    if current_user.email == 'guest_user_@example.com'
      redirect_to user_path(current_user), alert: 'ゲストユーザーの情報は変更・削除できません。'
    end
  end
end

app/helpers/health_cares_helper.rb
module HealthCaresHelper
  def health_care(value)
    value ||= '-'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/health_cares/_form.html.erb
<div class="form-group">
  <%= f.label :body_weight, "体重" %><br>
  <%= f.text_field :body_weight, class: "form-control" %><div class="col text-right">Kg</div>
</div>

<div class="form-group">
  <%= f.label :max_blood_pressure, "最高血圧" %><br>
  <%= f.text_field :max_blood_pressure, class: "form-control" %>
  <div class="col text-right">mmHg</div>
</div>

<div class="form-group">
  <%= f.label :min_blood_pressure, "最低血圧" %><br>
  <%= f.text_field :min_blood_pressure, class: "form-control" %>
  <div class="col text-right">mmHg</div>
</div>

<div class="form-group">
  <%= f.label :blood_sugar, "血糖値" %><br>
  <%= f.text_field :blood_sugar, class: "form-control" %>
  <div class="col text-right">mg/dL</div>
</div>

<% if local_assigns[:edit_flag].present? %>
  <p class="text-center"><%= f.submit "変更を保存", class: "btn btn-warning" %></p>
<% else %>
  <p class="text-center"><%= f.submit "新規登録", class: "btn btn-primary" %></p>
<% end %>

app/views/users/health_cares/_hospital.html.erb
<div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <h2><%= user.last_name %><%= user.first_name %>さんの健康管理</h2>
</div>

<div class="col-md-10 col-md-offset-1 col-sm-12">
  <% if health_cares.present? %>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th class="col text-center" style="vertical-align : middle;text-align:center;" >日付</th>
            <th class="col text-center" style="vertical-align : middle;text-align:center;">体重</th>
            <th colspan="2" class="col text-center">血圧<br>（最高・最低）</th>
            <th class="col text-center" style="vertical-align : middle;text-align:center;">血糖値</th>
          </tr>
        </thead>
        <tbody>
          <% health_cares.each do |health_care| %>
            <tr>
              <td class="col text-center"><%= health_care.date.strftime("%Y年%m月%d日") %></td>
              <td class="col text-center"><%= health_care(health_care.body_weight) %></td>
              <td class="col text-center"><%= health_care(health_care.max_blood_pressure) %></td>
              <td class="col text-center"><%= health_care(health_care.min_blood_pressure) %></td>
              <td class="col text-center"><%= health_care(health_care.blood_sugar) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <h3>特にありません</h3>
  <% end %>

  <div class="hospital-health_care-link text-right">
    <%= link_to "CSV出力", user_health_cares_path(format: :csv), class: "btn btn-success btn-lg" %>
    <%= link_to "患者マイページへ戻る", user_path(user), class: "btn btn-warning btn-lg" %>
  </div>
</div>

app/views/users/health_cares/_user.html.erb
<div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <h2>わたしの健康管理</h2>
</div>

<div class="col-md-10 col-md-offset-1 col-sm-12">
  <% if health_cares.present? %>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th class="col text-center" style="vertical-align : middle;text-align:center;" >日付</th>
            <th class="col text-center" style="vertical-align : middle;text-align:center;">体重</th>
            <th colspan="2" class="col text-center">血圧<br>（最高・最低）</th>
            <th class="col text-center" style="vertical-align : middle;text-align:center;">血糖値</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% health_cares.each do |health_care| %>
            <tr>
              <td class="col text-center"><%= health_care.date.strftime("%Y年%m月%d日") %></td>
              <td class="col text-center"><%= health_care(health_care.body_weight) %></td>
              <td class="col text-center"><%= health_care(health_care.max_blood_pressure) %></td>
              <td class="col text-center"><%= health_care(health_care.min_blood_pressure) %></td>
              <td class="col text-center"><%= health_care(health_care.blood_sugar) %></td>
              <td class="col text-center">
                <%= link_to "編集", edit_user_health_care_path(user_id: health_care.user_id, id: health_care.id), class: "btn btn-warning" %>
                <%= link_to "削除", user_health_care_path(user_id: health_care.user_id, id: health_care.id),
                method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <h3>特にありません</h3>
  <% end %>

  <div class="new-health_care-link text-right">
    <%= link_to "新しい数値を記録する", new_user_health_care_path(current_user), class: "btn btn-primary btn-lg" %>
    <%= link_to "CSV出力", user_health_cares_path(format: :csv), class: "btn btn-success btn-lg" %>
  </div>
</div>

app/views/users/health_cares/edit.html.erb
<div class="care-edit-container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
      <h2 class="health-header">健康管理の編集</h2>

        <div class="row">
          <%= form_with model: @health_care, url: user_health_care_path(@health_care), local: true do |f| %>
            <%= render "layouts/error", model: f.object %>
            <!--編集では、今日の日付をデフォルト入力しないため、日付カラムはrenderの外とする-->
            <div class="form-group">
              <%= f.label :date, "日付" %><br>
              <%= raw sprintf(
                f.date_select(
                  :date,
                  include_blank: true,
                  use_month_numbers: true,
                  start_year: Time.now.year,
                  end_year: 2020,
                  date_separator: "%s"),
                  "年", "月") +"日" %>
            </div>
            <%= render "form", f: f, health_care: @health_care, edit_flag: true %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/users/health_cares/index.html.erb
<div class="care-index-container">
  <div class="row">
    <% if @user == current_user %>
      <%= render "user", health_cares: @health_cares %>
    <% elsif current_hospital.patients?(@user) %>　<!--医療関係者でかかりつけ医登録場合-->
      <%= render "hospital", user: @user, health_cares: @health_cares %>
    <% end %>
  </div>
</div>

<%= paginate @health_cares %>

app/views/users/health_cares/new.html.erb
<div class="care-new-container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
      <h2 class="hea-header">健康管理の新規登録</h2>

        <div class="row">
          <%= form_with model: @health_care , url: user_health_cares_path(current_user), local: true do |f| %>
            <%= render "layouts/error", model: f.object %>
            <!--新規登録の場合み、今日の日付をデフォルト入力するため、日付カラムはrenderの外とする-->
            <div class="form-group">
              <%= f.label :date, "日付" %><br>
              <%= raw sprintf(
                f.date_select(
                  :date,
                  include_blank: true,
                  use_month_numbers: true,
                  selected: Date.today,
                  start_year: Time.now.year,
                  end_year: 2020,
                  date_separator: "%s"),
                  "年", "月") +"日" %><br>
            </div>
            <%= render "form", f: f, health_care: @health_care  %>
          <% end %>
        </div>
    </div>
  </div>
</div>